version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modulesv
      - /app/.next
    networks:
      - interconnect-network

  db:
    image: postgres:15-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=interconnect
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - interconnect-network

volumes:
  postgres_data:

networks:
  interconnect-network:
    driver: bridge
